import {
  SiJavascript,
  SiPython,
  SiCplusplus,
  SiC,
  SiRuby,
  SiPhp,
  SiSwift,
  SiKotlin,
  SiRust,
  SiGo,
  SiTypescript,
  SiHtml5,
  SiCss3,
  SiReact,
  SiAngular,
  SiVuedotjs,
  SiNodedotjs,
  SiExpress,
  SiDjango,
  SiFlask,
  SiLaravel,
  SiSpring,
  SiDotnet,
  SiMongodb,
  SiPostgresql,
  SiMysql,
  SiRedis,
  SiDocker,
  SiKubernetes,
  SiGit,
  SiGithub,
  SiGitlab,
  SiBitbucket,
  SiJira,
  SiConfluence,
  SiSlack,
  SiVercel,
  SiNetlify,
  SiHeroku,
  SiFirebase,
  SiSupabase,
  SiTailwindcss,
  SiBootstrap,
  SiChakraui,
  SiAntdesign,
  SiNextdotjs,
  SiGatsby,
  SiNuxtdotjs,
  SiSvelte,
  SiWebpack,
  SiBabel,
  SiJest,
  SiCypress,
  SiStorybook,
  SiPrettier,
  SiGradle,
  SiComposer,
  SiArduino,
  SiRaspberrypi,
  SiTensorflow,
  SiPytorch,
  SiScikitlearn,
  SiPandas,
  SiNumpy,
  SiJupyter,
} from 'react-icons/si';
import { FaJava } from 'react-icons/fa';
import { TbBrandCSharp } from 'react-icons/tb';

export const languageIcons = {
  javascript: SiJavascript,
  python: SiPython,
  'c++': SiCplusplus,
  c: SiC,
  java: FaJava,
  'c#': TbBrandCSharp,
  ruby: SiRuby,
  php: SiPhp,
  swift: SiSwift,
  kotlin: SiKotlin,
  rust: SiRust,
  go: SiGo,
  typescript: SiTypescript,
  html: SiHtml5,
  css: SiCss3,
  react: SiReact,
  angular: SiAngular,
  vue: SiVuedotjs,
  nodejs: SiNodedotjs,
  express: SiExpress,
  django: SiDjango,
  flask: SiFlask,
  laravel: SiLaravel,
  spring: SiSpring,
  dotnet: SiDotnet,
  mongodb: SiMongodb,
  postgresql: SiPostgresql,
  mysql: SiMysql,
  redis: SiRedis,
  docker: SiDocker,
  kubernetes: SiKubernetes,
  git: SiGit,
  github: SiGithub,
  gitlab: SiGitlab,
  bitbucket: SiBitbucket,
  jira: SiJira,
  confluence: SiConfluence,
  slack: SiSlack,
  vercel: SiVercel,
  netlify: SiNetlify,
  heroku: SiHeroku,
  firebase: SiFirebase,
  supabase: SiSupabase,
  tailwindcss: SiTailwindcss,
  bootstrap: SiBootstrap,
  chakraui: SiChakraui,
  antdesign: SiAntdesign,
  nextjs: SiNextdotjs,
  gatsby: SiGatsby,
  nuxtjs: SiNuxtdotjs,
  svelte: SiSvelte,
  webpack: SiWebpack,
  babel: SiBabel,
  jest: SiJest,
  cypress: SiCypress,
  storybook: SiStorybook,
  prettier: SiPrettier,
  gradle: SiGradle,
  composer: SiComposer,
  arduino: SiArduino,
  raspberrypi: SiRaspberrypi,
  tensorflow: SiTensorflow,
  pytorch: SiPytorch,
  scikitlearn: SiScikitlearn,
  pandas: SiPandas,
  numpy: SiNumpy,
  jupyter: SiJupyter,
}; 