import { useState } from "react";
import { CATEGORIES, SnippetForm } from "./components/SnippetForm";
import SnippetList from "./components/SnippetList";
import { IconButton } from "@mui/material";
import Brightness4Icon from '@mui/icons-material/Brightness4';
import Brightness7Icon from '@mui/icons-material/Brightness7';
import {
  atomDark,
  vs,
  vscDarkPlus,
  oneLight,
  oneDark,
  solarizedlight,
  solarizedDarkAtom,
  tomorrow
} from "react-syntax-highlighter/dist/esm/styles/prism";
import { github, githubGist } from "react-syntax-highlighter/dist/esm/styles/hljs";

// Project idea generated by ChatGPT and modified by Cursor
// https://chatgpt.com/share/67d3a2dc-7214-8000-b4e3-f67597b45c66
function App() {
  // states for adding snippets and languages
  const [snippets, setSnippets] = useState([]);
  const [languages, setLanguages] = useState([]);

  // states for filtering snippets
  const [selectedCategory, setSelectedCategory] = useState("All");
  const [selectedLanguage, setSelectedLanguage] = useState("All");

  // states for setting theme of web app
  const [isDarkMode, setIsDarkMode] = useState(true);
  const [theme, setTheme] = useState(atomDark);

  // filter snippets based on selected category
  const filteredSnippets = snippets.filter((s) => {
    const categoryMatch = selectedCategory === "All" || s.category === selectedCategory;
    const languageMatch = selectedLanguage === "All" || s.language === selectedLanguage;
    return categoryMatch && languageMatch;
  });

  // simple functions to add snippets and languages and delete snippets to be included in the components 
  // add a snippet to the list
  const addSnippet = (snippet) => {
    setSnippets([...snippets, snippet]);
  };

  // delete a snippet from the list
  const deleteSnippet = (index) => {
    setSnippets(snippets.filter((_, i) => i !== index));
  };

  // add a language to the list
  const addLanguage = (newLang) => {
    setLanguages([...languages, newLang]);
  };

  // Theme options for syntax highlighting
  const darkThemeOptions = {
    'Atom Dark': atomDark,
    'GitHub Dark': githubGist,
    'One Dark': oneDark,
    'Solarized Dark': solarizedDarkAtom,
    'VS Code Dark': vscDarkPlus
  };

  const lightThemeOptions = {
    'GitHub': github,
    'One Light': oneLight,
    'Solarized Light': solarizedlight,
    'Tomorrow': tomorrow,
    'Visual Studio': vs
  };

  // Toggle dark/light mode
  const toggleMode = () => {
    setIsDarkMode(!isDarkMode);
    // Update theme to first available theme in new mode
    const newModeThemes = isDarkMode ? lightThemeOptions : darkThemeOptions;
    setTheme(Object.values(newModeThemes)[0]);
  };

  // Get current theme options based on mode
  const currentThemeOptions = isDarkMode ? darkThemeOptions : lightThemeOptions;

  return (
    <div className="App" style={{
      backgroundColor: isDarkMode ? '#282c34' : '#ffffff',
      color: isDarkMode ? '#ffffff' : '#000000'
    }}>
      <div className="App-header">
        <div style={{ width: "50%", margin: "auto", paddingTop: "20px", paddingBottom: "20px" }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '10px' }}>
            <h2>Code Snippet Manager</h2>
            {/* toggle dark/light mode */}
            <IconButton onClick={toggleMode} color="inherit">
              {isDarkMode ? <Brightness7Icon /> : <Brightness4Icon />}
            </IconButton>
          </div>
          <p><em>Save your source code snippets in any programming language in one place</em></p>
          <div style={{ marginTop: "40px", marginBottom: "20px" }}>
            <h3>Add Snippet</h3>
          </div>
          {/* form component for adding a snippet */}
          <SnippetForm onSave={addSnippet} languages={languages} onAddLanguage={addLanguage} isDarkMode={isDarkMode} />
          <div style={{ marginTop: "40px", marginBottom: "20px" }}>
            <h3>Your Snippets</h3>
            {
              // show snippet list if there are snippets
              // otherwise show a message to add a snippet
              snippets.length > 0 ? (
                <>
                  <div style={{marginBottom: "20px"}}>
                    {/* theme selector */}
                    <label htmlFor="themeSelect">Select Theme: &nbsp;</label>
                    <select
                      value={Object.keys(currentThemeOptions).find(key => currentThemeOptions[key] === theme)}
                      onChange={(e) => setTheme(currentThemeOptions[e.target.value])}
                      style={{
                        padding: "8px",
                        borderRadius: "4px",
                        backgroundColor: isDarkMode ? "#3b3b3b" : "#ffffff",
                        border: "1px solid #ccc",
                        color: isDarkMode ? "#ffffff" : "#333",
                        width: "200px",
                        fontSize: "16px"
                      }}
                    >
                      {Object.keys(currentThemeOptions).map((themeName) => (
                        <option key={themeName} value={themeName}>
                          {themeName}
                        </option>
                      ))}
                    </select>
                  </div>
                  <label htmlFor="categorySelect">Select Category: &nbsp;</label>
                  <select
                    onChange={(e) => setSelectedCategory(e.target.value)} value={selectedCategory}
                    style={{
                      padding: "8px",
                      borderRadius: "4px",
                      backgroundColor: isDarkMode ? "#3b3b3b" : "#ffffff",
                      border: "1px solid #ccc",
                      color: isDarkMode ? "#ffffff" : "#333",
                      width: "200px",
                      fontSize: "16px",
                      marginBottom: "20px"
                    }}>
                    <option value="All">All</option>
                    {CATEGORIES.map((cat, index) => (
                      <option key={index} value={cat}>{cat}</option>
                    ))}
                  </select>
                  <label htmlFor="languageSelect">&nbsp; Select Language: &nbsp;</label>
                  <select onChange={(e) => setSelectedLanguage(e.target.value)} value={selectedLanguage}
                    style={{
                      padding: "8px",
                      borderRadius: "4px",
                      backgroundColor: isDarkMode ? "#3b3b3b" : "#ffffff",
                      border: "1px solid #ccc",
                      color: isDarkMode ? "#ffffff" : "#333",
                      width: "200px",
                      fontSize: "16px",
                      marginBottom: "20px"
                    }}>
                    <option value="All">All</option>
                    {languages.map((lang, index) => (
                      <option key={index} value={lang}>{lang}</option>
                    ))}
                  </select>
                  {
                    filteredSnippets.length > 0 ? (
                      <div style={{ marginTop: "40px", marginBottom: "20px" }}>
                        <SnippetList
                          snippets={filteredSnippets}
                          onDelete={deleteSnippet}
                          theme={theme}
                          isDarkMode={isDarkMode}
                        />
                      </div>
                    ) : (
                      <p>No snippets in this category yet. Add some more snippets to see them here!</p>
                    )
                  }
                </>
              ) : (
                <p>No snippets yet. Add one!</p>
              )
            }
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;